### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by mirjaj** [clandelius/alcorate#53]
The alcorate group has been very good at utilizing the milestones and issue tracker. The have consistently been adding new issues as they come further along in the implementation process. For example if they come up with new things they want to do, or find a bug. 

They have made great use of branching and pull requests. They have merged 40 times, and said in their presentations that doing this has made them become very comfortable with merges and the git work flow. 

The commit messages are inconsistent in quality, this is something they can improve in the last week. However the documentation, as well as the comments in the issues are good.

The project description is very good and informative. It tells you about how to use the product, and has a nice image as well.

**Comment by mirjaj** [comment]
Misunderstood how the merges get their numbers. They have merged several times though, but not that many :)

**Comment by slarse** [comment]
@ramtinmass @clandelius @navidha You can close this issue when you've read it.
